import { createFileRoute, Link } from "@tanstack/react-router";
import { useState } from "react";
import { Trash2 } from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { useCart } from "@/lib/cart";
export const Route = createFileRoute("/cart")({ component: CartPage });
function CartPage() { const cart = useCart(); const [busy, setBusy] = useState(false); const checkout = async () => { setBusy(true); const { data, error } = await supabase.functions.invoke("create-checkout", { body: { lines: cart.lines.map((line) => ({ productId: line.productId, variantId: line.variantId, quantity: line.quantity })), origin: window.location.origin } }); setBusy(false); if (error || !data?.url) return toast.error(error?.message || "Checkout could not be started"); window.location.assign(data.url as string); };
  return <main className="detail-page section-shell"><div className="shop-utility"><Link to="/">← Continue shopping</Link></div><h1>Your cart</h1>{cart.lines.length === 0 ? <div className="detail-card glass"><p>Your cart is empty.</p><Link className="listen-button" to="/" hash="merch">Browse merch</Link></div> : <div className="cart-layout"><div className="cart-lines">{cart.lines.map((line) => <article className="glass cart-line" key={`${line.productId}:${line.variantId ?? "default"}`}>{line.imageUrl && <img src={line.imageUrl} alt="" />}<div><strong>{line.name}</strong>{line.variantName && <span>{line.variantName}</span>}<span>${(line.unitPriceCents / 100).toFixed(2)}</span></div><input aria-label={`Quantity for ${line.name}`} type="number" min="1" max="99" value={line.quantity} onChange={(e) => cart.setQuantity(line.productId, line.variantId, Number(e.target.value))} /><button aria-label={`Remove ${line.name}`} onClick={() => cart.remove(line.productId, line.variantId)}><Trash2 /></button></article>)}</div><aside className="glass order-summary"><h2>Order summary</h2><p><span>Subtotal</span><strong>${(cart.subtotal / 100).toFixed(2)}</strong></p><small>Shipping and taxes are calculated securely at checkout.</small><button className="listen-button" disabled={busy} onClick={() => void checkout()}>{busy ? "Opening checkout…" : "Secure checkout"}</button></aside></div>}</main>;
}
