/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ShopSlugRouteImport } from './routes/shop.$slug'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as CheckoutCancelledRouteImport } from './routes/checkout.cancelled'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSectionsRouteImport } from './routes/admin.sections'
import { Route as AdminMusicRouteImport } from './routes/admin.music'
import { Route as AdminMerchRouteImport } from './routes/admin.merch'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminLinksRouteImport } from './routes/admin.links'
import { Route as AdminLegalRouteImport } from './routes/admin.legal'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminArtistRouteImport } from './routes/admin.artist'

const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/shop/$slug',
  path: '/shop/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutCancelledRoute = CheckoutCancelledRouteImport.update({
  id: '/checkout/cancelled',
  path: '/checkout/cancelled',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSectionsRoute = AdminSectionsRouteImport.update({
  id: '/sections',
  path: '/sections',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMusicRoute = AdminMusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMerchRoute = AdminMerchRouteImport.update({
  id: '/merch',
  path: '/merch',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLinksRoute = AdminLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLegalRoute = AdminLegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArtistRoute = AdminArtistRouteImport.update({
  id: '/artist',
  path: '/artist',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/admin/artist': typeof AdminArtistRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/legal': typeof AdminLegalRoute
  '/admin/links': typeof AdminLinksRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/merch': typeof AdminMerchRoute
  '/admin/music': typeof AdminMusicRoute
  '/admin/sections': typeof AdminSectionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/checkout/cancelled': typeof CheckoutCancelledRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/events/$slug': typeof EventsSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/admin/artist': typeof AdminArtistRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/legal': typeof AdminLegalRoute
  '/admin/links': typeof AdminLinksRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/merch': typeof AdminMerchRoute
  '/admin/music': typeof AdminMusicRoute
  '/admin/sections': typeof AdminSectionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/checkout/cancelled': typeof CheckoutCancelledRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/events/$slug': typeof EventsSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/admin/artist': typeof AdminArtistRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/legal': typeof AdminLegalRoute
  '/admin/links': typeof AdminLinksRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/merch': typeof AdminMerchRoute
  '/admin/music': typeof AdminMusicRoute
  '/admin/sections': typeof AdminSectionsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/checkout/cancelled': typeof CheckoutCancelledRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/events/$slug': typeof EventsSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cart'
    | '/admin/artist'
    | '/admin/events'
    | '/admin/legal'
    | '/admin/links'
    | '/admin/media'
    | '/admin/merch'
    | '/admin/music'
    | '/admin/sections'
    | '/admin/settings'
    | '/checkout/cancelled'
    | '/checkout/success'
    | '/events/$slug'
    | '/shop/$slug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/admin/artist'
    | '/admin/events'
    | '/admin/legal'
    | '/admin/links'
    | '/admin/media'
    | '/admin/merch'
    | '/admin/music'
    | '/admin/sections'
    | '/admin/settings'
    | '/checkout/cancelled'
    | '/checkout/success'
    | '/events/$slug'
    | '/shop/$slug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cart'
    | '/admin/artist'
    | '/admin/events'
    | '/admin/legal'
    | '/admin/links'
    | '/admin/media'
    | '/admin/merch'
    | '/admin/music'
    | '/admin/sections'
    | '/admin/settings'
    | '/checkout/cancelled'
    | '/checkout/success'
    | '/events/$slug'
    | '/shop/$slug'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutCancelledRoute: typeof CheckoutCancelledRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  EventsSlugRoute: typeof EventsSlugRoute
  ShopSlugRoute: typeof ShopSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/shop/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/cancelled': {
      id: '/checkout/cancelled'
      path: '/checkout/cancelled'
      fullPath: '/checkout/cancelled'
      preLoaderRoute: typeof CheckoutCancelledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sections': {
      id: '/admin/sections'
      path: '/sections'
      fullPath: '/admin/sections'
      preLoaderRoute: typeof AdminSectionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/music': {
      id: '/admin/music'
      path: '/music'
      fullPath: '/admin/music'
      preLoaderRoute: typeof AdminMusicRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/merch': {
      id: '/admin/merch'
      path: '/merch'
      fullPath: '/admin/merch'
      preLoaderRoute: typeof AdminMerchRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/links': {
      id: '/admin/links'
      path: '/links'
      fullPath: '/admin/links'
      preLoaderRoute: typeof AdminLinksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/legal': {
      id: '/admin/legal'
      path: '/legal'
      fullPath: '/admin/legal'
      preLoaderRoute: typeof AdminLegalRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/artist': {
      id: '/admin/artist'
      path: '/artist'
      fullPath: '/admin/artist'
      preLoaderRoute: typeof AdminArtistRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminArtistRoute: typeof AdminArtistRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminLegalRoute: typeof AdminLegalRoute
  AdminLinksRoute: typeof AdminLinksRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminMerchRoute: typeof AdminMerchRoute
  AdminMusicRoute: typeof AdminMusicRoute
  AdminSectionsRoute: typeof AdminSectionsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminArtistRoute: AdminArtistRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminLegalRoute: AdminLegalRoute,
  AdminLinksRoute: AdminLinksRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminMerchRoute: AdminMerchRoute,
  AdminMusicRoute: AdminMusicRoute,
  AdminSectionsRoute: AdminSectionsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutCancelledRoute: CheckoutCancelledRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  EventsSlugRoute: EventsSlugRoute,
  ShopSlugRoute: ShopSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
